// bosschat_engine_safari.js — 从文件读取注入Safari
window.BossChat={};
BossChat.gc=function(idx){var c=document.querySelectorAll('li.job-card-box')[idx];if(!c)return'||';var ne=c.querySelector('.job-name');var ce=c.querySelector('.boss-info');var lk=c.querySelector('a.job-name');return(ne?ne.textContent.trim():'')+'|'+(ce?ce.textContent.trim():'')+'|'+(lk?lk.getAttribute('href'):'')};
BossChat.qt=function(){var d=new Date().toDateString();var s=localStorage.getItem('qdate')||'';var c=parseInt(localStorage.getItem('qcount')||'0');if(s!==d){localStorage.setItem('qdate',d);localStorage.setItem('qcount','0');c=0}return(150-c)+''};
BossChat.uq=function(){var c=parseInt(localStorage.getItem('qcount')||'0');localStorage.setItem('qcount',''+(c+1))};
BossChat.tf=function(){var el=document.querySelector('.job-detail-body')||document.querySelector('.job-sec-text');if(!el)return'';var t=el.textContent.toLowerCase().substring(0,3000);var k='笔试,做题,测评,测试题,在线测试,机试,编程题,算法题,线上笔试,上机考试'.split(',');for(var i=0;i<k.length;i++){if(t.indexOf(k[i])>=0)return k[i]}return''};
BossChat.os=function(){var cn='';var cl=document.querySelector('.boss-name');if(cl)cn=cl.textContent.trim();else{var ls=document.querySelectorAll('a[href*="/gongsi/"]');for(var i=0;i<ls.length;i++){var t=ls[i].textContent.trim();if(t.length>1&&t.length<25&&t!='公司'&&t.indexOf('查看')<0&&t.indexOf('更多')<0){cn=t;break}}}var bl='中软国际,软通动力,文思海辉,东软集团,博彦科技,亚信科技,法本信息,诚迈科技,润和软件,汉得信息,外企德科,中智,科锐国际,华为od,富士康,立讯精密'.split(',');for(var i=0;i<bl.length;i++){if(cn.indexOf(bl[i])>=0)return cn}return''};
BossChat.ac=function(){var el=document.querySelector('.boss-active-time');if(!el)return'no';var t=el.textContent;if(t.indexOf('在线')>=0)return'today';if(t.indexOf('刚刚活跃')>=0)return'today';if(t.indexOf('今日活跃')>=0)return'today';if(t.indexOf('昨日活跃')>=0)return'yesterday';return'no'};
BossChat.sc=function(){try{var r=JSON.parse(localStorage.getItem('bosschat_resume')||'{}');var el=document.querySelector('.job-detail-body')||document.querySelector('.job-sec-text');if(!el)return'0|0|0|0|0|?';var txt=el.textContent.toLowerCase().substring(0,5000);var sk=r.skills||[];var mc=0;for(var i=0;i<sk.length;i++){if(txt.indexOf(sk[i].toLowerCase())>=0)mc++};var sk2=r.kw||[];for(var i=0;i<sk2.length;i++){if(txt.indexOf(sk2[i].toLowerCase())>=0)mc++};var ss=Math.min(50,mc*8);var hi=document.querySelector('.job-header-info');var ht=hi?hi.textContent:'';var em=ht.match(/([0-9]+)年以上/);if(!em)em=ht.match(/([0-9]+)[-~]([0-9]+) *年/);var nx=em?[em[2]||em[1]]:null;var re=nx?parseInt(nx[0]):0;var es=re>0?(Math.abs(10-re)<=1?30:Math.abs(10-re)<=3?20:10):20;var ed=txt.indexOf('本科')>=0?'本科':txt.indexOf('硕士')>=0?'硕士':'';var order={博士:4,硕士:3,本科:2,大专:1};var eu=r.education||'本科';var eus=ed?((order[eu]||0)>=(order[ed]||0)?20:5):15;return(ss+es+eus)+'|'+ss+'|'+es+'|'+eus+'|'+re+'|'+(ed||'?')}catch(e){return'0|0|0|0|0|err'}};
BossChat.cb=function(){var btn=document.querySelector('a.op-btn.op-btn-chat,a.btn.btn-startchat');if(btn){btn.click();return'yes'}return'no'};
BossChat.sb=function(){var sb=document.querySelector('span.btn.btn-outline.btn-cancel');if(sb&&sb.textContent.indexOf('留在此页')>=0)sb.click();else{var sb2=document.querySelector('.greet-boss-footer .cancel-btn');if(sb2)sb2.click()}};
BossChat._addLog=function(t){var el=document.getElementById('bc-log-panel');if(!el){el=document.createElement('div');el.id='bc-log-panel';el.style.cssText='position:fixed;top:60px;right:10px;width:360px;max-height:70vh;overflow-y:auto;background:rgba(0,0,0,0.85);color:#0f0;font:12px/1.5 monospace;padding:10px;border-radius:6px;z-index:99999;white-space:pre-wrap';document.body.appendChild(el)}var d=document.createElement('div');d.textContent=t;el.appendChild(d);el.scrollTop=el.scrollHeight};
BossChat._scrollToLoad=function(){try{for(var t=0;t<5;t++){var before=document.querySelectorAll('li.job-card-box').length;window.scrollTo(0,document.body.scrollHeight);new Promise(function(r){setTimeout(r,800)});var after=document.querySelectorAll('li.job-card-box').length;if(after>before)return after+''}return document.querySelectorAll('li.job-card-box').length+''}catch(e){return'0'}};
BossChat._closePopup=function(){var btns=document.querySelectorAll('[ka=dialog_close],.greet-boss-header .close,.dialog-header .close,.popup-close,.close-btn');for(var i=0;i<btns.length;i++){if(btns[i].offsetParent!==null){btns[i].click();return'closed'}}return'nopopup'};
